services:
  typescript-app:
    build:
      context: .
    container_name: typescript-app
    restart: unless-stopped
    init: true
    # env_file: ./.env  # Uncomment if .env file exists
    ports:
      - "4173:4173"  # Expose Vite preview server
    networks:
      - appnet
    # The app may require access to Firebase or Supabase, but these are cloud services and not run as containers

networks:
  appnet:
    driver: bridge
